### ISSUE TITLE
cache context please

### ISSUE THREAD

**Issue by ndushay** [ruby-rdf/json-ld#13]
It seems that json-ld  is not caching context documents, and I strongly feel it should.  I was temporarily blocked from w3c due to this lack of caching.

I see in the gemspec that there is a *development* dependency on open-uri-cached;  however, i believe the actual code in question is doing a Net::HTTP.get  request
  https://github.com/ruby-rdf/json-ld/blob/develop/lib/json/ld/api.rb#L463
called from 
  https://github.com/ruby-rdf/json-ld/blob/master/lib/json/ld/context.rb#L292

so the open-uri-cached gem is perhaps not in play.   In any case, I think this should be a production default.

Thanks!
- Naomi

**Comment by Gargron** [comment]
@gkellogg Could you provide an example of how to hook up the documentLoader with Rails.cache? I tried but got weird recursion errors, so I am not sure how that option/method is supposed to look.

**Comment by gkellogg** [comment]
Sorry, I'm out for a bit with surgery, so can't respond well right now. There may be some in the respec directory, I used rack-client-components.

**Comment by floze** [comment]
I hope you are OK Gregg. Your work is invaluable to me, but a fellow here once said: "Health is not everything, but without health, everything is nothing". All the best wishes from an avid user.

**Comment by gkellogg** [comment]
I haven't used this in a while, due to instability in rest-client and rest-client-components, however the RDF.rb gem has a `RestClientAdaptor`, based on `HttpAdapter`. If rest-client-components is loaded, then this should enable the rest-client cache to be used for requests.

From 85eb3d7502ef2a834d9d734b11eb6dab785e6beb, set up RestClient as follows (or however you normally stet up Rack caching:

```
require 'restclient/components'
require 'rack/cache'

# Create and maintain a cache of downloaded URIs
URI_CACHE = File.expand_path(File.join(File.dirname(__FILE__), "uri-cache"))
Dir.mkdir(URI_CACHE) unless File.directory?(URI_CACHE)
# Cache client requests
RestClient.enable Rack::Cache,
  verbose:      true, 
  metastore:   "file:" + ::File.expand_path("../uri-cache/meta", __FILE__),
  entitystore: "file:" + ::File.expand_path("../uri-cache/body", __FILE__)
```

In `RDF::Util::File`, if the `:use_net_http` is not set, and `RestClient` is defined, it will use the `RestClientAdapter`, or you can set `RDF::Util::File.http_adapter` explicitly in a global. See http://www.rubydoc.info/gems/rdf/RDF/Util/File.

You can also use your own `documentLoader`, as an option to any JSON-LD API call, and `documentLoader` is called with other API options. The built-in `documentLoader` invokes `RDF::Util::File.open_file` with passed options.

If things have settled back out, I would accept a PR to re-enable client caching when for tests. Otherwise, it's intended to be set up in a persistent service.
